services:
  - type: web
    name: servisin-backend
    env: php
    buildCommand:
      - "composer install --no-dev --ignore-platform-reqs"
      - "php artisan key:generate"
      - "php artisan migrate --force"
      - "php artisan storage:link"
    startCommand: "php artisan serve --host=0.0.0.0 --port=8000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: servisin-backend
          property: url
      - key: SESSION_DRIVER
        value: database
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: servisin-db
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        fromDatabase:
          name: servisin-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: servisin-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: servisin-db
          property: password
